<?php

namespace AppBundle\Repository;

/**
 * BaseTvShowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseTvShowRepository extends \Doctrine\ORM\EntityRepository
{
}
