<?php

namespace AppBundle\Repository;

/**
 * BrowseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrowseRepository extends \Doctrine\ORM\EntityRepository
{
}
