<?php

namespace AppBundle\Repository;

/**
 * TrendingMovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrendingMovieRepository extends \Doctrine\ORM\EntityRepository
{
}
