<?php

namespace AppBundle\Repository;

/**
 * TvEpisodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TvEpisodeRepository extends \Doctrine\ORM\EntityRepository
{
}
