<?php

namespace AppBundle\Repository;

/**
 * TvProductionCompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TvProductionCompanyRepository extends \Doctrine\ORM\EntityRepository
{
}
