<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Watched;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\OptimisticLockException;

/**
 * WatchedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WatchedRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManagerInterface $em,
                                Mapping\ClassMetadata $metaData = null)
    {
        parent::__construct($em,
            $metaData == null ?
                new Mapping\ClassMetadata(Watched::class) :
                $metaData);
    }

    /**
     * @param Watched $id
     * @return bool
     * @throws \Doctrine\ORM\ORMException
     */
    public function insert(Watched $id)
    {
        try {
            $this->_em->persist($id);
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }
}
